### ISSUE TITLE
SubscriptionTopic R4B/R5

### ISSUE THREAD

**Issue by lukeaduncan** [IHE/ITI.DSUBm#1]
Should there be some management of SubscriptionTopics as outlined in R4B/R5?  I'm not sure the R4B implementation has everything needed so maybe this needs to wait until an R5 update, but it seems worth a discussion.

**Comment by JohnMoehrke** [comment]
https://hl7.org/fhir/uv/subscriptions-backport/

**Comment by scontento** [comment]
Decide to use R4B and https://hl7.org/fhir/uv/subscriptions-backport/
