### ISSUE TITLE
DSUBm_002: AuditEvent profiling is not done due to use of R4B

### ISSUE THREAD

**Issue by scontento** [IHE/ITI.DSUBm#10]
(see DSUBm_002 in issues.html)
The AuditEvents for each transaction are not yet profiled bacause the IG publisher, at the moment, does not allow to further constrain a Profile coming from a different FHIR version of the IG.

**Comment by scontento** [comment]
If we are going to switch to R4 we can use the BALP profile. 
Otherwise, if we decide to remain in R4B, we could recreate what we need of BALP inside DSUBm

**Comment by scontento** [comment]
Decided to switch to R4 will use BALP.

**Comment by gpavan19** [comment]
profiled the AuditEvents for each transactions
