### ISSUE TITLE
DSUBm_004: ITI-112 expected actions

### ISSUE THREAD

**Issue by scontento** [IHE/ITI.DSUBm#12]
(see DSUBm_004 in issues.html)
For the [Resource Notify [ITI-112]](https://profiles.ihe.net/ITI/DSUBm/1.0.0-comment/ITI-112.html) transaction the DSUBm profiles the expected action for the Resource Notification Broker in order to define a common way to manage errors and connection problems that may occur for all the different type of notifications. Considering the various infrastructure capabilities with which the subscription framework could be implemented, should the expected action be revised? Is it appropriate to define the number of attempts after the first error for the [Heartbeat Notification Message](https://profiles.ihe.net/ITI/DSUBm/1.0.0-comment/ITI-112.html#231126-heartbeat-notification-message) and the [Event Notification Message](https://profiles.ihe.net/ITI/DSUBm/1.0.0-comment/ITI-112.html#231127-event-notification-message)? Are there other points to focus on?

**Comment by gpavan19** [comment]
related to #36 and #37

**Comment by RicardoQuintano** [comment]
I don't think it should define a number of attempts for the Heartbeat/Event notification. After all, an error will be sent to the Recipient.

A related question came to my mind: how the Recipient (subscriber) knows that the subscription is not active anymore due to a connection error?  Does the Recipient know this with a "Subscription Deactivation Notification Request Message"? Does it know as it does not receive anymore the "Heartbeat Notification Request Message"?

**Comment by GinoCanessa** [comment]
This is a tough case to specify up-front, since actual tolerances are going to be use-case specific.  I generally lean towards specifying that people need to consider and implement *something*, but leave concrete numbers out of it.

**Comment by scontento** [comment]
We agree that a specific number should not be defined in the expected action.
At the moment in section "2:3.112.8.3 Expected Actions" we indicated that:  

`
"If the Resource Notification Broker receives a negative response (based on the HTTP status or the OperationOutcome received), it should immediately set the Subscription.status=error or it COULD do that after a reasonable number of times. This should be done based on the capability of the connection infrastructure."
`
Is this sufficient or we should expand on that?
Maybe we can specify something about the connection error handling as written below..

Regarding the question "how the Recipient (subscriber) knows that the subscription is not active anymore due to a connection error? " 

- if the heartbeat period has been indicated in the Subscription resource and after an N +1 heartbeat periods  no "Heartbeat Notification Request Message" has been received by the Recipient then the Recipient should treat the Subscription in error 
(see  2:3.112.8.3 Expected Actions:
`
If the Resource Notification Broker receives a negative response (based on the HTTP status or the OperationOutcome received), it should immediately set the Subscription.status=error 
`
)
- otherwise, if the heartbeat period has not been used in the Subscription resource, there will be no "Heartbeat Notification Request Message" sent by the Broker and in this case the Subscriber could use the $status operation to check the status of the subscription resource. 
 
We should also consider that these could be best-practice suggestions for the implementers and we could add this consideration in the section "2:3.112.13 Handling Errors in Notification".

**Comment by scontento** [comment]
Discussed and closed.
