### ISSUE TITLE
DSUBm_006: replicate MHD due to FHIR R4B use

### ISSUE THREAD

**Issue by scontento** [IHE/ITI.DSUBm#14]
If the following resource are directly used (with dependency) from MHD profiles: 
 - Minimal DocumentReference 
 - Minimal SubmissionSet
 - Minimal Folder
 
there are the following errors in the QA report : 

- The reference http://hl7.org/fhir/ValueSet/identifier-use|4.0.1 could not be resolved
- The reference http://hl7.org/fhir/ValueSet/list-status|4.0.1 could not be resolved
- The reference http://hl7.org/fhir/ValueSet/list-mode|4.0.1 could not be resolved
- The reference http://hl7.org/fhir/ValueSet/c80-doc-typecodes could not be resolved
- The reference http://hl7.org/fhir/ValueSet/document-classcodes could not be resolved
- The reference http://hl7.org/fhir/ValueSet/document-relationship-type|4.0.1 could not be resolved

- The constraint 'dom-3' has an expression 'contained.where((('#'+id in (%resource.descendants().reference | %resource.descendants().as(canonical) | %resource.descendants().as(uri) | %resource.descendants().as(url))) or descendants().where(reference = '#').exists() or descendants().where(as(canonical) = '#').exists() or descendants().where(as(canonical) = '#').exists()).not()).trace('unmatched', id).empty()', which differs from the earlier expression provided of 'contained.where(((id.exists() and ('#'+id in (%resource.descendants().reference | %resource.descendants().as(canonical) | %resource.descendants().as(uri) | %resource.descendants().as(url)))) or descendants().where(reference = '#').exists() or descendants().where(as(canonical) = '#').exists() or descendants().where(as(uri) = '#').exists()).not()).trace('unmatched', id).empty()' (invariants are allowed to repeat, but cannot differ)

(see comparison Domain resource from R4 and R4B).

The TEMPORARY SOLUTION for now is to replicate some MHD content that is used in DSUBm in R4B. (files in folder "DSUBm_DocumentRelatedResources")

**Comment by GinoCanessa** [comment]
Per other issues (#65 , #9 ), I think that moving to FHIR R4 is a better alternative than recreating content from MHD.

**Comment by scontento** [comment]
Switched from R4B to R4, not needed anymore. MHD used in the dependecies.
