### ISSUE TITLE
Location of response message section in transactions.

### ISSUE THREAD

**Issue by lukeaduncan** [IHE/ITI.DSUBm#19]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

3.110, 3.112, 3.113

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

The response messages should be right after the request message when there are multiple messages for the transaction instead of all the requests followed by all the responses.

**Proposed Change** 

Place the response sections directly after the request sections

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by scontento** [comment]
Ok, this would mean that 

ITI-110 will have the following new order: 

- 2:3.110.5 Create Subscription Request Message
- 2:3.110.6 Create Subscription Response Message
- 2:3.110.7 Update Subscription Request Message
- 2:3.110.8 Update Subscription Response Message


ITI-112 will have the following new order: 

- 2:3.112.5 Handshake Notification Request Message
- 2:3.112.6 Handshake Notification Response Message
- 2:3.112.7 Heartbeat Notification Request Message
- 2:3.112.8 Heartbeat Notification Resonse Message
- 2:3.112.9 Event Notification Request Message
- 2:3.112.10 Event Notification Response Message
- 2:3.112.11 Subscription Deactivation Notification Request Message
- 2:3.112.12 Subscription Deactivation Notification Response Message

ITI-113 will have the following new order: 

- 3.113.5 Subscription Search Request Message
- 3.113.6 Subscription Search Response Message
- 3.113.7 Subscription Status Search Request Message
- 3.113.8 Subscription Status Search Response Message
- 3.113.9 Subscription Events Search Request Message
- 3.113.10 Subscription Events Search Response Message

I have created a branch for this issue and I have started working on it.
