### ISSUE TITLE
FHIR create for notification transaction

### ISSUE THREAD

**Issue by lukeaduncan** [IHE/ITI.DSUBm#20]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

3.112

**Issue** 

Should the transaction be based off a FHIR Create interaction?  You mention the URL format that should be used, but for create that would be POST to BASE/Bundle which may not be the case since this is a notification to the Subscription endpoint.  Also I don't think the recipient should process it as a create since it doesn't need to create the Bundle, it just processes the notification.

**Proposed Change** 

Don't base the notifications on FHIR create.

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by scontento** [comment]
Issue resolved in PR #21 (see branch "19-location-of-response-message-section-in-transactions")

I edited the file and now we do not refer to the FHIR create interaction.
 
Now the request is a POST of the Bundle. 
the Response are 

- 200 OK with no body  (for the succesful communication)
or
- 4xx or 5xx with OperationOutcome if necessary.  

NOTE that the branch "[20-fhir-create-for-notification-transaction](https://github.com/IHE/ITI.DSUBm/tree/20-fhir-create-for-notification-transaction)" has NOT been used. 
(Therefore the branch 20-fhir-create-for-notification-transaction is useless)

**Comment by scontento** [comment]
resolved
