### ISSUE TITLE
Introduction is written like work item, not like profile

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#23]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

DSUBm Home

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

The first two paragraphs of the DSUBm Home page say that IHE does not provide a common framework for subscribing to document sharing artifacts. However, that is the purpose of this IG, so IHE does do that with this IG. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

I think the first two paragraphs can simply be removed. 

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by gpavan19** [comment]
agree, these sentences were written in the first stage of editing
