### ISSUE TITLE
Use Case #1 Is Really two

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#24]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

1:54.4.2

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

Use Case #1 describes two subscriptions for very different purposes. These seem like separate use cases. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Split Use Case #1 into two use cases. 

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by gpavan19** [comment]
The use case is also the complex scenario.

The purpose of the use case is also to show how different type of subscription can be performed towards a unique Broker from different Subscribers which may have different needs.
