### ISSUE TITLE
Use Case 2 Has ITI-68 With Wrong Actor

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#25]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

1:54.4.2.2.2

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

This use case shows the ITI-68 transaction happening between the MHD Document Consumer and the MHD Document Source. However, the MHD Document Source does not participate in the ITI-68 transaction. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

The transaction should be between the MHD Document Consumer and the MHDS Document Registry. 

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by gpavan19** [comment]
@scontento to fix point 5 and 9 of the use case, and check description below
