### ISSUE TITLE
Cross Profile Diagrams Don't Match Descriptions

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#26]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

1:54.6

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

The descriptions of how to group cross profile actors don't align with the diagrams. 

For Figure 1:54.6.1-1, you say:

"MHDS Document Registry will most likely be grouped with a Resource Notification Publisher because all publication events are submitted to the MHDS Document Registry.
MHDS Document Registry will likely be grouped with a Resource Notification Broker."

These are two alternatives, but the diagram only shows the MHD Document Responder and the DSUBm Resource Notification Publisher as being grouped. 

You also say:

"The MHD Document Consumer will most likely be grouped with a Resource Notification Recipient. This grouping makes sense since the receiver of the notification is most likely the user of the information.
The MHD Document Consumer, will likely be grouped with a Resource Notification Subscriber."

But the MHD Document Consumer is only shown grouped with the DSUBm Resource Notification Recipient. I think the DSUBm Resource Notification Subscriber should also be included in that grouping. 

Figure 1:54.6.2-1 is similarly affected. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Create alternative diagrams to show common groupings, and ensure diagrams match the suggestions in the text. 

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by gpavan19** [comment]
we can add two more diagrams, one per sections, to represent all the possible groupings describe.  @scontento
