### ISSUE TITLE
ITI-110 Consider Deferring to MHD for parameter definitions

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#27]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

2:3.110.8

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

Each subscription topic in ITI-110 lists the filter parameters and defines them. The definitions appear to be copied from MHD. Would it be better to simply list the parameters and simply link to MHD for the definitions? Doing so would ensure the definitions are always the same between the two profiles. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Link to MHD for the filter parameter definitions rather than duplicating them in DSUBm

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by gpavan19** [comment]
agree to simply list the parameters and simply link to MHD sections for the definitions
