### ISSUE TITLE
Notification Shape Need Not Include Patient Resource

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#28]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

SubscriptionTopic Artifacts

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

The Notification Shapes for the subscription topics all specify Includes of <Resource>:patient&iterate=Patient.link. I think including the Patient in the notification is unnecessary. In many cases, the Notification Recipient might already have the patient's identifier or FHIR ID cached, so it does not need the Patient Resource. If it does, it can always do a FHIR read to get the Patient. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Do not include the "includes" in the SubscriptionTopic instances. 

- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by gpavan19** [comment]
The notificationShape.includes does not mandate that the resurce shall be include. It indicate the resources that MAY be include in the notification (see https://hl7.org/fhir/R4B/subscriptiontopic.html#shape-additional-resources).

But we can eliminate it from the SubscriptionTopic instances.
