### ISSUE TITLE
Subscription.endpoint should be 1..1

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#29]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

Subscription Profiles

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

When the channel type is rest-hook, Subscription.endpoint is needed so that the Resource Notification Broker can send notifications to the Resource Notification Recipient. However, the Subscription Profiles in the IG have channel.type=rest-hook but endpoint is 0..1.

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Update the profiles to make endpoint 1..1

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by gpavan19** [comment]
agree
