### ISSUE TITLE
Should filtering by list.identifier be allowed?

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#30]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

2:3.110.8.3

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

`identifier` is listed as a criteria parameter for the Patient-Dependent Folder Subscription Topic. I'm not sure that makes sense as a filter parameter, since I wouldn't expect multiple Folders to be created with the same identifier. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Remove `identifier` from the list of criteria parameters. 

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by gpavan19** [comment]
The rationale could make sense but it does not imply that it will not be use in a Subscription framework.

This parameter is listed because it is a query parameter admitted for MHD and also could match against $XDSDocumentEntryPatientId in the mapping with XDS; so for me it is a valid parameter for a Subscription.

**Comment by slagesse-epic** [comment]
I don't see how List.identifier would be used to filter by $XDSDocumentEntryPatientId. I would expect DocumentReference.subject be used for that purpose.

**Comment by gpavan19** [comment]
sorry, I confuse with patient.identifier.

The List.identifier parameter should be used to subscribe for the List.identifier that point to Folder.entryUUID or Folder.uniqueId metadata in XDS

So, when I subscribe for  Patient's Folders , I can subscribe directly using the UUID or uniqueId point exactly to the desired Folder

**Comment by slagesse-epic** [comment]
But what is the purpose of subscribing to a specific folder? If the folder is already created, how would any notifications be generated?

**Comment by gpavan19** [comment]
For the Folder, the SubscriptionTopic includes also the updates (based on what one can do with MHD ). So when the Folder is updated, adding a DocumentReference for example, the notification is sent.

**Comment by slagesse-epic** [comment]
In that case, my question is why the base Folder topic includes update when none of the other base topics do, and we have an extra option specifically for handling update?

**Comment by gpavan19** [comment]
The update option consider the creation, uptate and deletion for all the resource. 
For the Folder, based that MHD already consider the update at base, the base topic already consder it.

**Comment by slagesse-epic** [comment]
I see. Okay, I think that makes sense for this issue. I think my remaining concern can be addressed in #32.
