### ISSUE TITLE
Use Case for Subscribing To SubmissionSets

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#31]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

2:3.110.8.4

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

SubscriptionTopics are provided that allow the subscriber to subscribe to SubmissionSets. However, I don't see anything in the use cases to suggest this functionality is needed. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

If there is a use case for subscribing to SubmissionSets, include one in the use cases section. If not, then remove the SubmissionSet topics. 

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by gpavan19** [comment]
we can point out the use for this type of subscription in the use cases section @scontento
