### ISSUE TITLE
Folder Topics Should be Optional

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#32]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

2:3.114.5.3

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

Right now, it is required for the Resource Notification Broker to support the Patient-Dependent Folder SubscriptionTopic. Resource Notification Brokers might not support Folder objects, so support for this topic should be optional. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Make an option for support of the Patient-Dependent Folder SubscriptionTopic. 

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by gpavan19** [comment]
Requires further analysis on which subscription/SubscriptionTopic types should be added and what a Resource Notification Broker shall or may support. There could be also other type of subscription that could be added.

Possibly related to #33

**Comment by gpavan19** [comment]
@slagesse-epic I agree but the solution is affected also by the issue #33 and required at least the split of the already present option. Please, take a look on what I have reported there (#33) in order to make the most significant options.
