### ISSUE TITLE
Provide Option For Subscribing to Just Create, Delete, and Update on Status

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#33]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

1:54.2.1

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

Right now, when the Updates to document sharing resources option is not implemented, only Create events generate notifications. When that option is implemented, then all create, update, and delete events shall be reported. 

Resource Notification Brokers that are not operating as native FHIR servers might not have the ability to notify for all Updates. However, I think the most common updates that a Resource Notification Recipient will be interested in are changes to the status element of the subject resource. So, it would be useful to have an option where only the following events need to be reported on:

Create
Update of status only
Delete

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Create an option that allows Resource Notification Brokers to notify on resource Create and Delete, and updates to the .status element only. 

**Priority**:
- High: Important issue where there is major issue to be resolved. Requires discussion and debate.

**Comment by gpavan19** [comment]
Requires further analysis on which subscription/SubscriptionTopic types should be added and what a Resource Notification Broker shall or may support. There could be also other type of subscription that could be added.

Possibly related to #32

**Comment by gpavan19** [comment]
I agree but I think the solution could be more refined, broadening the reasoning on the maximum effort that we could required to a Resource Notification Broker, and also in agreement with issue #32.

So, from the prospective of a Resource Notification Subscriber and Recipient I thought about what are the most significant topics and events that I would consider and it make sense to support them. Also, from the prospective of a Resource Notification Brokers I thought about what are the most significant topics and events that I would be able to support and it make sense to support them. 

In agreement with issue #32, the conlusion was to redefine the options in this way:

0) basic topics consider (minumum requirement for DSUBm profile without any option):
	- create DocumentReference
	- create SumbissionSet
	
1) "Basic Folder Subscription Option" adds topic that consider:
	- create, update only to add new .entry.item in Folder (consider creation and only new document insert in Folder)

2) "Folder Subscription for Minimal Update Option" adds topic that consider:
	- create, update to add or remove .entry.item and update status on Folder (consider new document insert in Folder, document remove from Folder and status update)

3) "Folder Subscription for Update Option" adds topic that consider:
	- create, update Folder (consider all possible updates on Folder)

4) "Folder Subscription for Full Events Option" adds topic that consider:
	- create, update, delete Folder (consider all possible events on Folder)

5) "DocumentReference Subscription for Minimal Update Option" adds topic that consider:
	- create, update only status, delete DocumentReference
	
6) "DocumentReference Subscription for Full Events Option" adds topic that consider:
	- create, update, delete DocumentReference (consider all possible events on DocumentReference)

The options increment the effort on the Resource Notification Broker and extend the previous Topics for the subscriptions on that Resource. It means that if for example the Resource Notification Broker support the option 6), it support also the topic of option 5).

Note that these Options introduce only new definition of SubscriptionTopic (and Subscriptions which reference them) in ITI-110 page and artifacts (instances, profile and capabilityStatement) end moving a couple of sections.

I don't know if I went beyond the scope of this issue, but reasoning about the maximum effort that we could required to a Resource Notification Broker brings these options. @slagesse-epic let me know if the options seem fine or there are some issues about.

**Comment by slagesse-epic** [comment]
These look reasonable to me.
