### ISSUE TITLE
Must a Resource Notification Broker Support All Filter Criteria?

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#34]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

2:3.110.5.3

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

The section states that the Resource Notification Broker shall verify that "all requested filters are defined in the requested topic and are implemented in the Resource Notification Broker"

Must the Resource Notification Broker implement all of the filters defined in this IG? Or is it allowed to support only some of them?

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Clarify the expectations of which filter parameters are supported by the Resource Notification Broker. 

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by gpavan19** [comment]
the Resource Notification Broker shall support all the filter parameter that are expresed in the SubscriptionTopic (canFilterBy parameters) which the Broker support

we clarify it
