### ISSUE TITLE
Subscription Update Also Needed For Error Recovery

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#36]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

2:3.110.6

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

The section states:

"This message uses the HTTP PUT method on the target Resource Notification Broker endpoint to update an existing Subscription resource in order to deactivate it and unsubscribe."

However, I think this message is also needed to re-activate a subscription that has been deactivated due to errors. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Allow using the Update Subscription message to re-activate errored subscriptions. 

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by gpavan19** [comment]
The purpose of the update now is only to deactivate the subscription.

This issue could be related to the #37 and [DSUBm_004](https://github.com/IHE/ITI.DSUBm/issues/12) about managing the errors.

The Resource Notification Subscriber shall always perform another subscription by posting a Subscription Resource with the same creteria when a Subscription goes in error or goes off. 

Further, if the Resource Notification Broker continues to try sending notification even in "error" status, the reacivation is not necessary until the Subscription goes off. Then again the Resource Notification Subscriber shall always perform another subscription.

**Comment by slagesse-epic** [comment]
This goes against the recommendation of the [Recovering from Errors section](https://build.fhir.org/ig/HL7/fhir-subscription-backport-ig/errors.html#recovering-from-errors) of the backport IG.

"Once an application has returned to a functional state, it should request the subscription is reactivated by updating the status to either requested or active as appropriate."

**Comment by gpavan19** [comment]
I think it is not a mandate, but it is a "should". So I think it is not againts.

But I can understand that could be usefull.

We can integrate it considering only the update with status to "requested" so that the Resource Notification Broker shall perform the handshake to verify the connection befor effectivelly reactivate the Subscription (as in the Subscription creation).

Does it fit for you? @slagesse-epic

**Comment by slagesse-epic** [comment]
Yes, that sounds good to me.
