### ISSUE TITLE
Deactivated Subscription Status

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#37]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

2:3.112.6.3

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

The text says:

"If the Resource Notification Broker has been able to send the Handshake Notification Message but it has not received any [Hearthbeat Notification Message](https://build.fhir.org/ig/IHE/ITI.DSUBm/branches/master/ITI-112.html#231126-heartbeat-notification-message) from the Resource Notification Recipient, it should deactivate the Subscription, setting the Subscription.status=error."

Based on text in FHIR R5 and the backport IG, it seems the intent is that a deactivated subscription has a status of `off`, while `error` simply means there was at least one error. 

From the [subscription-status code system](http://hl7.org/fhir/R4B/codesystem-subscription-status.html#subscription-status-error):

<html>
<body>

error | Error | The server has an error executing the notification.
-- | -- | --
off | Off | Too many errors have occurred or the subscription has expired.

</body>
</html>

From the [Handling Errors section of the backport IG](https://build.fhir.org/ig/HL7/fhir-subscription-backport-ig/errors.html)

"A server MAY:

Continue to send heartbeat messages (with an error status set)."

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Clarify when the status should be `error` vs `off` and the Notification Broker's expected actions for each state. 

**Priority**:
- High: Important issue where there is major issue to be resolved. Requires discussion and debate.

**Comment by gpavan19** [comment]
Related to issue [DSUBm_004](https://github.com/IHE/ITI.DSUBm/issues/12) and issue #36 

That is about how to proper handling the error and define a common way to implement the management of error when sending notification.

Based on text in FHIR R5 and the backport IG, there is no clear specification about when using or not using the status "error". And how many error should occur before setting to "off" a Subscription ?

A common sense implementation could be done evaluating a resonable number of consecutive error in the notifications (handshake, event o heartbeat) sended to the Recipient before totally deactivate the Subscription, and trying to send for a resonable period the notification anyway ; e.g. of a process flow:

- Handshake notification sent successfully -> activation of the subscription
- Heartbeat notification sent successfully -> maintain the status to active
- 1° Event notification goes wrong -> set the status to error
- Heartbeat notification goes wrong -> maintain the status to error
- 2° Event notification  sent successfully  -> set the status to active
- Heartbeat notification sent successfully -> maintain the status to active

The missing events could be retrieve with the $events operation with ITI-113 or by a query (ITI-67 or ITI-66) based on the impelmented logic.

**Comment by gpavan19** [comment]
I think that we could clarify the use of status "off" and "error" and use in proper way the word "deactivation" in ITI-112.
I think the consideration in the expected action should be always in a recommendend way.

Basically: 
- after the first error in the notification (any type except Deactivation) the Resource Notification Broker shall set the status to "error". It should continue to send other hearthbeat notification with status=error and it may continue to send other event notification (if events occur) with status=error.
- if the errors continue in hearthbeat notification or event notification, after a certain amount of error (according with the application implementation) the Resource Notification Broker should set the status to "off".

Does it fit for you ? @slagesse-epic

**Comment by slagesse-epic** [comment]
Yes, that seems good to me.
