### ISSUE TITLE
Strange requirement in ITI-114

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#40]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

2:3.114.5.2

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

The Description of the status search parameter says:  "Should be valued with active"

Is this trying to say that the Resource Notification Subscriber _must_ supply the status parameter with the value of "active"? This seems unnecessarily restrictive. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Allow the Resource Notification Subscriber to specify the status parameter as needed. 

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by gpavan19** [comment]
the purpose was not to force the Resource Notification Subscriber to set the status parameter to "active". 

the value "active" should be the racommended value when searching towards a Resource Notification Broker.

@scontento  we will clarfy it in the parameter description
