### ISSUE TITLE
Unclear How ITI-113 Used in DSUB

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#41]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

26.2.2

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

The IG adds an option to DSUB to use the ITI-113 transaction, but it is not clear how the DSUB actors would use such a transaction. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Clarify the transaction interaction expectations for DSUB actors implementing ITI-113. 

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by gpavan19** [comment]
We can add clarification on section 26.2.2 about the expectation fo DSUB actors implementing the transaction for the PC.

I think this issue is related to [DSUBm_0003](https://github.com/IHE/ITI.DSUBm/issues/11) issue of the profile.
