### ISSUE TITLE
Need to fixup header numbering in Volume 2

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.DSUBm#60]
The section heading levels are wrong. (For example 2:3.110.5 should be 2:3.110.4.1 and then everything underneath needs to be updated, too. This is true for all the transaction pages).

I then realized that my changes broke any internal references to the section numbers (because I changed them).

I reverted the 2 files I updated (ITI-110 and ITI-11) back to the original content. I think for public comment we should leave then as is and I can submit comments about this during the public comment period.

Mary

**Comment by JohnMoehrke** [comment]
Will leave these as they are for Public-Comment. Fix before Trial-Implementation.

**Comment by scontento** [comment]
I will do the edits for the end of this week.

**Comment by gpavan19** [comment]
fixed with the PC editing
