### ISSUE TITLE
Conformance Language Formatting

### ISSUE THREAD

**Issue by GinoCanessa** [IHE/ITI.DSUBm#64]
**Section Number**
All sections.

**Issue**
BCP 14 indicates that "only UPPERCASE usage of the key words have the defined special meanings."  I see many instances of lowercase conformance language (e.g., shall) and no instances of uppercase.  Is the intention that none of these are actually conformance language, or are they missing the correct casing?

**Proposed Change**
Reviewing all instances of conformance language to set correct casing.

**Priority**:
I believe this is *High*, as it sets conformance expectations.

**Comment by scontento** [comment]
@MaryLJ

**Comment by MaryLJ** [comment]
Verifying proper case for conformance language will be added as a publishing checklist item

**Comment by scontento** [comment]
I will do it for the end of the week.

**Comment by gpavan19** [comment]
done in the last editing
