### ISSUE TITLE
FHIR Version Dependency

### ISSUE THREAD

**Issue by GinoCanessa** [IHE/ITI.DSUBm#65]
**Section Number**
2:3.11x.3 Referenced Standards

**Issue**
FHIR R4B is not widely implemented and I do not expect to see that change.

**Proposed Change**
Backport IG STU 1.2 (currently in ballot) and tooling improvements brought functional parity for FHIR R4 and R4B in subscriptions.  I recommend moving DSUBm to FHIR R4 for wider compatibility.

Note that STU 1.2 also adds functionality for "Notified Pull".

**Priority**:
- High: Important issue where there is major issue to be resolved. Requires discussion and debate.

**Comment by scontento** [comment]
Hi @GinoCanessa,

When the ballot for the Backport IG STU 1.2 should end?

**Comment by scontento** [comment]
Thanks. Noted and moved to R4.
