### ISSUE TITLE
FHIR R4 SubscriptionTopic Search

### ISSUE THREAD

**Issue by GinoCanessa** [IHE/ITI.DSUBm#66]
**Section Number**
2:3.114 Resource SubscriptionTopic Search [ITI-114]

**Issue**
Given my recommendation to move to FHIR R4 (see issue #65), this section would need to be updated to cover `Basic` resources that use cross-version extensions to represent a SubscriptionTopic.

**Proposed Change**
Either expand this section to cover both options (using either R4B+ with SubscriptionTopic and R4 with Basic) or add another section covering Basic resource usage.

**Priority**:
- High: Important issue where there is major issue to be resolved. Requires discussion and debate.

**Comment by gpavan19** [comment]
discuss with the commmitee

agree R4 is better

we procede to switch to R4, maintaining the transaction and not having a section for R4B

**Comment by gpavan19** [comment]
integrated in the last editing
