### ISSUE TITLE
Heartbeat Conformance Level

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#67]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

2:3.110.5.3 and 2:3.112.7.1

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

These sections are not consistent with whether the Resource Notification Broken SHOULD or SHALL send heartbeat messages if requested. 

Section 2:3.110.5.3 says "When the Subscription Resource uses the heartbeatPeriod, if accepted, the Resource Notification Broker 'should' send one [Heartbeat Notification Message [ITI-112]](https://build.fhir.org/ig/IHE/ITI.DSUBm/branches/master/ITI-112.html#231127-heartbeat-notification-request-message) per interval on the accepted and active subscription."

2:3.112.7.1 says

"If in the Subscription the heartbeatPeriod element is set, the Resource Notification Broker 'shall' attempt to send a Heartbeat Notification Message after each interval set in that element."

So, it is unclear if this expectation is SHOULD or SHALL.

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Use consistent conformance language in both sections. 

**Priority**:

- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by scontento** [comment]
Thanks. 
Noted I will make the edit for tomorrow

**Comment by gpavan19** [comment]
It is a SHOULD, according with https://hl7.org/fhir/subscriptionstatus.html#heartbeat-notification

**Comment by gpavan19** [comment]
resolved
