### ISSUE TITLE
Figure 1:54.4.2.8.2-1 Wrong Transaction Name

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#71]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

Figure 1:54.4.2.8.2-1

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

In the figure, the transaction name for ITI-53 is "Document Metadata Publish". It should be "Document Metadata Notify".

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Correct to "Document Metadata Notify"

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by gpavan19** [comment]
typos to be fixed
