### ISSUE TITLE
Notification Shape Unclear

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#72]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

2:3.112.4.5.2

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

The text in this section says

"Note that Resource Notification Broker SHOULD attempt to provide the resources described in the topic, however Resource Notification Recipient SHALL expect that any resource beyond the focus resource are not guaranteed to be present."

However, none of the SubscriptionTopics specify anything other than the focus resource in their notification shape, as far as I can tell. But some of the event notification Bundle profiles include a Patient resource. So this seems overall inconsistent. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Either update the notification shape to include Patient or remove Patient from the event notification bundle profiles and the text stating that the Broker SHOULD attempt to provide such resources. 

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by gpavan19** [comment]
reviewed: update the notification shape to include Patient
