### ISSUE TITLE
References to DSUBmlistTypes

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#74]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

"SubscriptionTopic: SubscriptionTopic for Folder Patient-Dependent resource with Basic Folder Subscription Option"
"SubscriptionTopic: SubscriptionTopic for Folder Subscription for Full Events Option"
"SubscriptionTopic: SubscriptionTopic for Folder Subscription for Minimal Update Option"
"SubscriptionTopic: SubscriptionTopic for Folder Subscription for Update Option" 
"SubscriptionTopic: SubscriptionTopic for SubmissionSet Multi-Patient resource"
"SubscriptionTopic: SubscriptionTopic for SubmissionSet PatientDependent resource" 

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

The fhirpaths for these topics all reference a DSUBmlistTypes valueset that I don't think exists anymore. Is this a hold over from the R4B->R4 conversion?

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

I think these should only reference the MHDlistTypes valueset. 

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by gpavan19** [comment]
typos to be fixed
