### ISSUE TITLE
Two profiles called "SubscriptionStatus for the handshake event"

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#75]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

Artifacts

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

There are two profiles called "SubscriptionStatus for the handshake event"

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Rename the profiles to differentiate them. Is one of them supposed to be a heartbeat?

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by gpavan19** [comment]
typos to be fixed. one is for hearthbeat
