### ISSUE TITLE
Unused ValueSets

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#76]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

ValueSet: DSUBm List Types ValueSet
ValueSet: Restful-interaction available
CodeSystem: DSUBm Fhir Type

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

I am not sure what these Artifacts are used for.  Can they be removed?

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

If they are unused, remove. If they are needed, clarify what purpose they serve. 

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by gpavan19** [comment]
removed because not used.
