### ISSUE TITLE
Build warning on incorrect use of canonical URI

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.DSUBm#84]
The new publisher is complaining that you are putting a canonical into a reference.

The examples
Instance: ex-AuditQueryResourceSubscriptionTopicReadSubscriber
and 
Instance: ex-AuditQueryResourceSubscriptionTopicReadBroker

are using the canonical in entity. What is the use of this?  

* entity[data].what.reference = "https://profiles.ihe.net/ITI/DSUBm/SubscriptionTopic/DSUBm-SubscriptionTopic-DocumentReference-MultiPatient"

Should these not be using the created subscription?

**Comment by JohnMoehrke** [comment]
I am going to publish with this warning, not put it in ignore warnings as I can't tell if it should be ignored.

**Comment by gpavan19** [comment]
The reference in the Audit for the read event of the "Subscription Topic" should point to the Basic resource retrieved by the Subscriber. My thought was to point to the canonical Basic resource defined in the profile (that represents the SubscriptionTopic in R4) for a  certain topic. 
But, now I think that in a real case there shall be a Basic resource in the Resource Notification Broker, that shall be the same as the Basic canonical resource for a certain topic, but with a "local" Id, that could be read like in a fhir server.

So we can create an example of the Basic resource for a certain topic to be used in the audit example for the read operation.

**Comment by gpavan19** [comment]
I don't know if I can point directly to a canonical instances using the reference to the Id. 

But if I try, the Reference(Basic/DSUBm-SubscriptionTopic-DocumentReference-MultiPatient) could not be resolve by the builder. Instead the Reference(SubscriptionTopic/DSUBm-SubscriptionTopic-DocumentReference-MultiPatient) is resolved but it point to a SubscriptonTopic resource instead to a Basic, that in not correct. And this is in the current master.

**Comment by gpavan19** [comment]
The other thing that I can see is that the publisher doesn't generete the warning with:

entity[data].what = Reference(SubscriptionTopic/DSUBm-SubscriptionTopic-DocumentReference-MultiPatient)

that is in the current master.

**Comment by JohnMoehrke** [comment]
appears to be no longer an issue
